"use strict";
const STATUS_CODE={
	SUCCESS:200,
	UNPROCESSABLE_ENTITY:201,
	FORBIDDEN:202,
	ACCEPTED:203,
	NOT_FOUND:207,
	BAD_REQUEST:205,
	UNAUTHORIZED:206,
};
module.exports = {
	STATUS_CODE:STATUS_CODE
};

